added order functionality
suprun-anna/book-store pull request #13
Opened 2024-03-01 17:48 UTC by suprun-anna

created order and orderItem models, dtos, mappers, repositories, service, controller, liquibase files for creating tables

2024-03-01 18:39 UTC, MentorMA requested changes

2024-03-01 18:39 UTC, MentorMA commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        return orderMapper.toDto(order);
Please divide some logic to separate method, cause this method too big

2024-03-01 19:37 UTC, okuzan requested changes

2024-03-01 19:37 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: /db/changelog/changes/18-insert-cart-items.yaml
```suggestion
      file: /db/changelog/changes/18-insert-cart-items.yaml
      
```

2024-03-01 19:37 UTC, okuzan commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
> +                () -> new RuntimeException("Can't find user by id= " + id));
combine into one line, throw EntityNotFound

2024-03-01 19:37 UTC, okuzan commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
>                  () -> new RuntimeException("Can't find user by email " + email));
throw EntityNotFoundException

2024-03-01 19:37 UTC, okuzan commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        }
[throw early](https://softwareengineering.stackexchange.com/questions/18454/should-i-return-from-a-function-early-or-use-an-if-statement), unnest rest of your code

2024-03-01 19:37 UTC, okuzan commented on src/main/java/mate/academy/bookstore/mapper/OrderMapper.java
> +    @Mappings({
```suggestion
```
you can just stack them one by one

2024-03-01 19:37 UTC, okuzan commented on src/main/java/mate/academy/bookstore/mapper/OrderItemMapper.java
> +    @Mappings({
same

2024-03-02 12:48 UTC, MentorMA approved these changes

2024-03-02 12:49 UTC, merged