created specification builder, providers, provider manager
suprun-anna/book-store pull request #6
Opened 2024-02-14 19:12 UTC by suprun-anna

2024-02-15 15:50 UTC, okuzan requested changes
Well done!

2024-02-15 15:50 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/BookSpecificationProviderManager.java
> +                .orElseThrow(() -> new RuntimeException("Can't find correct "
better to throw more specific exception where possible, let's go for NoSuchElement here for example

2024-02-15 18:18 UTC, MentorMA requested changes

2024-02-15 18:18 UTC, MentorMA commented on src/main/java/mate/academy/bookstore/repository/BookSpecificationBuilder.java
> +                            .getSpecification(searchParams.isbns()));
Duplication code, divide logic cause you have too big method

2024-02-16 13:26 UTC, okuzan approved these changes

2024-02-16 13:26 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/BookSpecificationProviderManager.java
> +                .filter(p -> p.getKey().equals(key))
change p to provider, uninformative naming is a bad idea even for stream chains

2024-02-16 14:22 UTC, merged